### ISSUE TITLE
Bug report: I can't run the game

### ISSUE THREAD

**Issue by vitorueno** [kauereblin/astroside-game#1]
## Describing the bug:

After cloning the repository and executing the steps to run the game, I've got an exception that apparently shows that it couldn't find a file called **ground.tsx** from your personal files: **\prog\projetos\python\kaue\leak\maps**.

### Python version I've used:

> Python 3.8.3

### Describing the steps to reproduce the bug:

1. Clone the repo
2. Create the virtual environment using  **venv**: `python -m venv env`
3. Install the requirements from requirements.txt into the venv: `python -m pip install -r requirements.txt`
4. run `python astroside/main.py`

### Listing the packages inside my virtual environment:

Package |   Version
|---------- |-------|
|numpy   |   1.18.4 |
|pip        |19.2.3 |
|pygame   |  1.9.6 | 
|PyTMX    |  3.21.7 |
|setuptools | 41.2.0 |
|six      | 1.14.0 |

## Error message

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Cannot load external tileset: D:\prog\projetos\python\kaue\leak\maps\ground.tsx
Traceback (most recent call last):
  File "D:\prog\projetos\python\kaue\astroside-game\env\lib\site-packages\pytmx\pytmx.py", line 870, in parse_xml
    node = ElementTree.parse(path).getroot()
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38-32\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Users\vitor\AppData\Local\Programs\Python\Python38-32\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\prog\\projetos\\python\\kaue\\leak\\maps\\ground.tsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "astroside/main.py", line 265, in <module>
    main()
  File "astroside/main.py", line 260, in main
    game = Game()
  File "astroside/main.py", line 38, in __init__
    self.load_tilemap(self.map_id)
  File "astroside/main.py", line 162, in load_tilemap
    self.current_map = Tilemap(
  File "D:\prog\projetos\python\kaue\astroside-game\astroside\classes\tilemap.py", line 10, in __init__
    self.map = ptx.load_pygame(filename, pixelalpha=True)
  File "D:\prog\projetos\python\kaue\astroside-game\env\lib\site-packages\pytmx\util_pygame.py", line 141, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
  File "D:\prog\projetos\python\kaue\astroside-game\env\lib\site-packages\pytmx\pytmx.py", line 360, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "D:\prog\projetos\python\kaue\astroside-game\env\lib\site-packages\pytmx\pytmx.py", line 400, in parse_xml
    self.add_tileset(TiledTileset(self, subnode))
  File "D:\prog\projetos\python\kaue\astroside-game\env\lib\site-packages\pytmx\pytmx.py", line 845, in __init__
    self.parse_xml(node)
  File "D:\prog\projetos\python\kaue\astroside-game\env\lib\site-packages\pytmx\pytmx.py", line 874, in parse_xml
    raise Exception
Exception

**Comment by kauereblin** [comment]
Sorry, I was editing the textures I used in the game, but for some reason I didn't see the commit, where I removed the unedited files and didn't put them back.
I'll put in next commit.
Thank you!
That was worse than I expected.
